### ISSUE TITLE
I have set it up according to instructions but I always cross origin policy error

### ISSUE THREAD

**Issue by sajjadsaleem** [odonata95/laravel-angular-boilerplate#2]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/Server/register. (Reason: CORS header â€˜Access-Control-Allow-Originâ€™ missing).

**Comment by odonata95** [comment]
Restart your server

On May 11, 2018 16:02, "sajjadsaleem" <notifications@github.com> wrote:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at http://localhost/Server/register. (Reason: CORS header
â€˜Access-Control-Allow-Originâ€™ missing).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/odonata95/laravel-angular-boilerplate/issues/2>, or mute
the thread

**Comment by odonata95** [comment]
Try to restart your server.
If this does not help, check that you follow the instructions #1

**Comment by sajjadsaleem** [comment]
I tried all this but it is still not working, cross origin issue is coming
My angular front-end is at at  http://localhost:4200 and Server at http://localhost/api

**Comment by odonata95** [comment]
maybe you have wrong setting on your server

**Comment by sajjadsaleem** [comment]
@odonata95 
What could they be?

**Comment by odonata95** [comment]
Did you try to change your server URL from http://localhost/ to something else (like http://test/)? Which PHP server do you use (Wamp, Denwer)? I'm using Wamp and I did not have such a mistake. It looks like you have a badly configured server. Try to send request from Postman to see if the server is responding to requests. If not - try to configure it right.

**Comment by sajjadsaleem** [comment]
@odonata95 I have fixed it. I am using ubuntu and and there was a problem in my virtual host configuration. I had to write "AllowOverride All" for my root directory. Thanks for your help.
